/**
 * Progressive Web App Service Worker (sw.js)
 * Generated by PWA Generator Utility
 * Caching Strategy: CACHE-FIRST
 */

const CACHE_NAME = 'html-com-ly-cache-v1';
const PRECACHE_ASSETS = [
  "./",
  "./index.html",
  "./manifest.json",
  "./favicon.ico",
  "./icon-192.png",
  "./icon-512.png"
];

// 1. Install Event: Pre-cache essential assets & force activation
self.addEventListener('install', (event) => {
  console.log('[SW] Service Worker installing...');
  event.waitUntil(
    caches.open(CACHE_NAME)
      .then((cache) => {
        console.log('[SW] Pre-caching core application assets...');
        return cache.addAll(PRECACHE_ASSETS);
      })
      .then(() => {
        console.log('[SW] Core assets cached successfully. Skipping waiting phase.');
        return self.skipWaiting();
      })
      .catch((error) => {
        console.error('[SW] Pre-caching failed during installation:', error);
      })
  );
});

// 2. Activate Event: Clean up legacy caches & claim clients
self.addEventListener('activate', (event) => {
  console.log('[SW] Service Worker activating...');
  event.waitUntil(
    caches.keys()
      .then((cacheNames) => {
        return Promise.all(
          cacheNames.map((existingCache) => {
            if (existingCache !== CACHE_NAME) {
              console.log('[SW] Removing old cache version:', existingCache);
              return caches.delete(existingCache);
            }
          })
        );
      })
      .then(() => {
        console.log('[SW] Claiming clients for immediate control.');
        return self.clients.claim();
      })
  );
});

// 3. Fetch Event: Intercept network requests using cache-first caching strategy
self.addEventListener('fetch', (event) => {
  // Skip non-GET requests and browser extensions
  if (event.request.method !== 'GET' || !event.request.url.startsWith('http')) {
    return;
  }

  // Cache First Strategy with Network Fallback
  event.respondWith(
    caches.match(event.request).then((cachedResponse) => {
      if (cachedResponse) {
        return cachedResponse;
      }
      return fetch(event.request).then((networkResponse) => {
        if (!networkResponse || networkResponse.status !== 200 || networkResponse.type !== 'basic') {
          return networkResponse;
        }
        const responseToCache = networkResponse.clone();
        caches.open(CACHE_NAME).then((cache) => {
          cache.put(event.request, responseToCache);
        });
        return networkResponse;
      }).catch(() => {
        // If offline and requesting HTML, serve cached main page
        if (event.request.headers.get('accept')?.includes('text/html')) {
          return caches.match('./index.html');
        }
      });
    })
  );
});
// Push Notification Event Listener
self.addEventListener('push', (event) => {
  const data = event.data ? event.data.text() : 'Default notification from PWA';
  event.waitUntil(
    self.registration.showNotification('PWA Notification', {
      body: data,
      icon: './icon-192.png',
      badge: './icon-192.png',
    })
  );
});

// Background Sync Event Listener
self.addEventListener('sync', (event) => {
  if (event.tag === 'pwa-sync-data') {
    console.log('[SW] Background sync triggered for tag:', event.tag);
    event.waitUntil(Promise.resolve());
  }
});

